apiVersion: v1
kind: Pod
metadata:
  name: myapp4
  labels:
    app: myapp
spec:
  containers:
  - name: my-app
    image: nginx
  tolerations:
  - key: "key4"
    operator: "Equal"
    value: "value4"
    effect: "NoSchedule"
