apiVersion: v1
kind: Pod
metadata:
  name: myapp5
  labels:
    app: myapp
spec:
  containers:
  - name: my-app
    image: nginx
  tolerations:
  - key: "key5"
    operator: "Equal"
    value: "value5"
    effect: "NoSchedule"